using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SOConstantsGenerators.Constants;

namespace SOConstantsGenerators;

[Generator]
public class SOPartialPartGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var provider = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateConstantsForAttributeContants.IDENTIFIER,
                predicate: static (syntaxNode, _) => syntaxNode is ClassDeclarationSyntax,
                transform: static (context, _) => Transform(context));

        context.RegisterSourceOutput(provider, Generate);
    }

    private static SOInfo Transform(GeneratorAttributeSyntaxContext context)
    {
        var classDecl = (ClassDeclarationSyntax)context.TargetNode;
        return new()
        {
            Name = classDecl.Identifier.ToString(),
            Namespace = Utilities.GetNamespace(classDecl),
        };
    }

    private static void Generate(SourceProductionContext context, SOInfo info)
    {
        GenerateOutputFolderField(context, info);
    }

    private static void GenerateOutputFolderField(SourceProductionContext context, SOInfo soInfo)
    {
        var sourceCode = $@"// <auto-generated />
#if UNITY_EDITOR
using SaintsField.Playa;
using SOConstantsGenerator;
using UnityEngine;
using UnityEditor;

namespace {soInfo.Namespace}
{{
    public partial class {soInfo.Name}
    {{
        [Header(""SO Constants Generator"")]
        public DefaultAsset OutputFolder;

        [LayoutStart(""Dynamic Fields"", ELayout.Horizontal)]
        [Button]
        private void GenerateDynamicFields() => ConstantsGeneratorHelper.GenerateDynamicFields(this);

        [LayoutCloseHere]
        [Button]
        private void LoadDynamicFields() => ConstantsGeneratorHelper.LoadDynamicFields(this);
        
        [Button]
        private void GenerateConstants() => ConstantsGeneratorHelper.GenerateConstants(this);
    }}
}}
#endif
";

        context.AddSource($"{soInfo.Namespace}.{soInfo.Name}.g.cs", sourceCode);
    }
}